curl localhost:8080 | jq '.dictionary["nāli"]'
curl localhost:8080 | jq '.glosses["nāli,noun"]'
curl localhost:8080 | jq '.concordance["nāli @ Hirsch @ .ABS @ noun @ "]'
curl localhost:8080 | jq '.corpus["KBo 32.14,Vs. 12a"]'
curl localhost:8080 | jq '.glosses["nāli,noun"]'
curl localhost:8080 | jq '.glosses["ed,verb"]'
curl localhost:8080 | jq '.glosses["ed,noun"]'
curl localhost:8080 | jq '.glosses["en,verb"]'
curl localhost:8080 | jq '.glosses["enn,verb"]'
curl localhost:8080 | jq '.corpus["KBo 32.14,Vs. 4a"]'
curl localhost:8080 | jq '.concordance["šid-ar-ill-ō-m @ verfluchen @ ITER-INGR-TR.PFV-3A.SG @ verb @ "]'
curl localhost:8080 | jq '.concordance["šid-ar-ill-ō-m @ verfluchen @ ITERAT-INGRESS-TR.PFV-3A.SG @ verb @ "]'
curl localhost:8080 | jq '.corpus["KBo 32.14,Rs. 11a"]'
