curl localhost:8080 | jq '.dictionary["nāli"]'
curl localhost:8080 | jq '.glosses["nāli,noun"]'
curl localhost:8080 | jq '.concordance["nāli @ Hirsch @ .ABS @ noun @ "]'
curl localhost:8080 | jq '.corpus["KBo 32.14,Vs. 12a"]'
curl localhost:8080 | jq '.glosses["nāli,noun"]'
curl localhost:8080 | jq '.glosses["ed,verb"]'
curl localhost:8080 | jq '.glosses["ed,noun"]'
curl localhost:8080 | jq '.glosses["en,verb"]'
curl localhost:8080 | jq '.glosses["enn,verb"]'
